### ISSUE TITLE
Text buttons color

### ISSUE THREAD

**Issue by ArturZahn** [d-Rickyy-b/webogram-x#6]
I had to modify it a bit to work (probably my issues trying to insert it on the page) so my report could not be a real issue, but those texts aren't looking right

![Sem titulo](https://user-images.githubusercontent.com/62709763/116559620-03caf600-a8d7-11eb-8cde-5c6f3effae80.png)
(I'm from Brazil)

edit: I fixed it with this

/* Buttons */

.btn-primary {
    color: var(--text-light) !important;
}

**Comment by d-Rickyy-b** [comment]
Hi there and thanks for reporting the issue.
What browser (& which version) are you using?

For me it looks like this:
![grafik](https://user-images.githubusercontent.com/5798157/116789854-56f8a080-aab1-11eb-93bb-0e8d7685d427.png)

**Comment by ArturZahn** [comment]
I'm using google chrome
But I tried it again with an other css injector and it worked, so I guess it isn't you code problem
